user www-data;
worker_processes auto;

events {
    worker_connections 768;
}

http {

    proxy_cache_path /home/nginx/cached
                     levels=1:2
                     keys_zone=my_cache:10m
                     max_size=10g
                     inactive=60m
                     use_temp_path=off;

    server {
        listen 3002;

        location / {
            # enable cache
            proxy_cache my_cache;

            # cache key based on method + host + URI + query string
	        # proxy_cache_key "$request_method$host$request_uri";

            # cache valid responses for 1 minute
            proxy_cache_valid 200 1m;
            proxy_cache_valid 404 1m;

            # prevent cache stampede on simultaneous requests
	        # proxy_cache_lock on;

            # serve stale cache if upstream is down
	        # proxy_cache_use_stale error timeout updating;

            # forward correct headers to upstream
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            # expose cache status in response header
            add_header X-Cache-Status $upstream_cache_status;

            proxy_pass http://localhost:3080;
        }
    }
}